### ISSUE TITLE
zsh: exec format error: notify-send-server

### ISSUE THREAD

**Issue by callistino** [fgrehm/notify-send-http#1]
Running into that issue when trying to start the server on Mac OSX with command:

```
PORT=12345 notify-send-server
```

It may be a zsh issue but I wanted to know if there was any way to diagnose. Also, I see the files have extension `.go`. Does that mean I need to install Go?

**Comment by fgrehm** [comment]
This might be related to the binary itself, along with 0.2.0 I cross compiled for Mac OSX, please LMK if it works for you!

Binaries are available at https://github.com/fgrehm/notify-send-http/releases/tag/v0.2.0
